Hospital.class: Admin.java Doctor.java DoctorMainMenu.java FrontDesk.java FrontDeskMainMenu.java Hospital.java Nurse.java NurseMainMenu.java Patient.java PatientMainMenu.java User.java Time.java Appointment.java Usertype.java
	javac -g Admin.java Doctor.java DoctorMainMenu.java FrontDesk.java FrontDeskMainMenu.java Hospital.java Nurse.java NurseMainMenu.java Patient.java PatientMainMenu.java User.java Time.java Appointment.java Usertype.java

run: Hospital.class
	java Hospital

clean: 
	rm -f *.class

debug:
	jdb Hospital
